### ISSUE TITLE
Show "All" is not working

### ISSUE THREAD

**Issue by rabe69** [Ecodev/vidi_frontend#50]
If change show selector to "All", an error 500 is returned from Ajax request.
The problem is the "-1" value, which throws an exception in line 195 of the Domain/Repository/ContentRepository of Extension vidi.

If changing this condition: 
`if ($limit) {
       $query->setLimit($limit);
 }`
to:
`if ($limit && $limit > 0) {
      $query->setLimit($limit);
}`
it should work.

**Comment by fabarea** [comment]
Thanks for the catch.

**Comment by fabarea** [comment]
Fixed via https://github.com/fabarea/vidi/issues/121
